#!/bin/sh
set -e

if [ "$UID" ]; then
	usermod -u "$UID" www-data
	groupmod -g "$UID" www-data
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"